# Generated by Django 4.2 on 2023-05-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.PositiveSmallIntegerField(choices=[(1, 'MANAGEMENT'), (2, 'SALES'), (3, 'SUPPORT')], default=1),
            preserve_default=False,
        ),
    ]
